### PR TITLE
New social image

### LINKED ISSUE #331: Social image still shows Gulp
https://twitter.com/dcorbacho/status/1277888555407364102

### PR DESCRIPTION
**Pull request by argyleink**
in #333 Una [shared](https://github.com/GoogleChromeLabs/tooling.report/pull/333#issuecomment-651766797) the social image embed from the web.dev post, this turns that idea into a pr 👍  this is the image used in the web.dev announcement post. 

the image was squooshed, but maybe @jakearchibald knows the best sliders to pull another 50k out the image? 
do we like this image better?

fixes #331

### CODE REVIEW

**Review by surma — COMMENTED** [review]
The file size of the social image went from 30 KB to 181 KB. Did you run this through Squoosh?

edit: Just saw that you did. But 181KB seems excessive. I’ll take a look.

**Comment by surma** [comment]
Do you have a high-res original somewhere to work with?

**Comment by argyleink** [comment]
fwiw, it's a bigger image, but yep! here's 2 different exports

tooling-report-social
tooling-report-social

**Comment by jakearchibald** [comment]
How do we feel about this @ 70k?

86261997-29cb2100-bb74-11ea-8821-77baf38078cd

Twitter recommends 1200x675.

**Comment by argyleink** [comment]
LGTM!

**Comment by jakearchibald** [comment]
Actually it's supposed to be 2:1, so here's a 65k version. I also used a better resize algo:

86261997-29cb2100-bb74-11ea-8821-77baf38078cd (2)

**Comment by argyleink** [comment]
nice, i was juuuuust about to push hehe

**Comment by jakearchibald** [comment]
That lighthouse score scares me, but I can't recreate it locally. Maybe a server issue?

**Comment by argyleink** [comment]
same! i was inspecting that as well, looks like a red herring / CI hiccup

**Comment by jakearchibald** [comment]
Let's pretend we didn't see it.

**Pull request merged**
