### PR TITLE
Update social image

### PR DESCRIPTION
**Pull request by jakearchibald**
Part of #331

### CODE REVIEW

**Comment by jakearchibald** [comment]
I think this counts as a quick fix. @argyleink and @una might want to come up with something better. Maybe we could look at generating one at build time? 😀

For this PR I just avoided showing stuff that can go out of date too easily, or wouldn't really matter if it goes out of date.

**Comment by jakearchibald** [comment]
Oh and I optimised some near-by images.

**Comment by una** [comment]
I really like this social image!

Screen Shot 2020-06-30 at 8 42 27 AM

**Comment by jakearchibald** [comment]
Ohh, yeah, that's good!

**Pull request merged**
